name: "build-and-release-android"
description: "Build the Android APK and Upload to GitHub"
inputs:
  tag_name:
    description: "Tag Name"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Setup Java
      id: setup-java
      uses: actions/setup-java@v4
      with:
        java-version: "17" # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        distribution: "corretto"

    - name: "Install Dependencies"
      id: install-dependencies
      uses: "./.github/actions/install-dependencies"

    - name: "Setup EAS"
      id: setup-eas
      uses: "./.github/actions/setup-eas"

    - name: Package Android Release
      shell: bash
      id: package
      run: |
        set -e

        cd app
        yarn prebuild
        eas build --local --platform=android --non-interactive --profile preview
        cd ..

        apk=$(ls ./app/*.apk | tail -1)
        echo "apk_asset_path=$apk" >> $GITHUB_OUTPUT
        echo "apk_asset_name=$(basename $apk)" >> $GITHUB_OUTPUT

    - name: Upload APK Release Assets for Android
      id: upload-apk
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ env.GITHUB_TOKEN }}
        file: ${{ steps.package.outputs.apk_asset_path }}
        asset_name: ${{ steps.package.outputs.apk_asset_name }}
        tag: ${{ inputs.tag_name }}
        overwrite: true
